spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web-order-db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  web:
    resources:
      static-locations: file:media/,classpath:/static
  mvc:
    hiddenmethod:
      filter:
        enabled: true
jwt:
  secret: xIjvWyzFNiIL16uC7Z4vtoY6nkCKk+wjN/ruzg8lkX6t09fC+qHWMRG+4RtoYakCOQWq1bmyYH34oab36pf8Tw==